---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  name: skupper-router
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-router
      skupper.io/component: router
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        application: skupper-router
        skupper.io/component: router
    spec:
      containers:
      - env:
        - name: APPLICATION_NAME
          value: skupper-router
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: QDROUTERD_AUTO_MESH_DISCOVERY
          value: QUERY
        - name: QDROUTERD_CONF
          value: |2
%s
        image: %s
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: router
        ports:
        - containerPort: 5671
          name: amqps
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 55671
          name: inter-router
          protocol: TCP
        - containerPort: 45671
          name: edge
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/qpid-dispatch-certs/skupper-amqps/
          name: skupper-amqps
        - mountPath: /etc/qpid-dispatch-certs/skupper-internal/
          name: skupper-internal
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: skupper
      serviceAccountName: skupper
      terminationGracePeriodSeconds: 30
      volumes:
      - name: skupper-amqps
        secret:
          defaultMode: 420
          secretName: skupper-amqps
      - name: skupper-internal
        secret:
          defaultMode: 420
          secretName: skupper-internal
---
