apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: qdrouterd
  name: console
spec:
  host: %s
  port:
    targetPort: console
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None